version: "3.6"

services:
  SplunkDev:
    image: ${SPLUNK_IMAGE:-splunk/splunk:latest}
    container_name: SplunkDev
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=changeme
    ports:
      - 8000:8000